# Generate Harness Constants
# ===========================
# Reads all schemas (schemas/*.json) and fixtures (schemas/fixtures/*.json)
# and outputs a JS file containing const declarations for embedding in harnesses.
#
# This is the CANONICAL embedding path. Harnesses MUST source their embedded
# constants from the output of this script -- never hand-maintain them.
#
# DRIFT RULE: Run this script any time a schema or fixture changes.
# Regeneration is deterministic. Verify freshness: regenerate and diff
# against the committed generated output. Non-empty diff = stale harness.
#
# Usage:
#   cd <repo-root>
#   .\tools\generate-harness-constants.ps1
#
#   Optional output path:
#   .\tools\generate-harness-constants.ps1 -OutFile harnesses\_constants.js
#
# Output file is placed at harnesses\_constants.js by default.

param(
  [string]$OutFile = "harnesses\_constants.js",
  [string]$RepoRoot = $PSScriptRoot + "\.."
)

$ErrorActionPreference = 'Stop'

$schemasDir  = Join-Path $RepoRoot "schemas"
$fixturesDir = Join-Path $schemasDir "fixtures"

if (-not (Test-Path $schemasDir)) {
  Write-Error "schemas/ directory not found at: $schemasDir"
  exit 1
}
if (-not (Test-Path $fixturesDir)) {
  Write-Error "schemas/fixtures/ directory not found at: $fixturesDir"
  exit 1
}

function ConvertTo-JsConstName {
  param([string]$filename)
  # "profile.schema.json"       -> "SCHEMA_PROFILE"
  # "full-profile-stage3.json"  -> "FIXTURE_FULL_PROFILE_STAGE3"
  # "invalid-broken-seal-chain.json" -> "FIXTURE_INVALID_BROKEN_SEAL_CHAIN"
  $base = [System.IO.Path]::GetFileNameWithoutExtension($filename)  # strip .json
  $base = $base -replace '\.schema$', ''                             # strip .schema
  $base = $base.ToUpper() -replace '[^A-Z0-9]', '_'
  if ($filename -match '\.schema\.json$') {
    return "SCHEMA_$base"
  } else {
    return "FIXTURE_$base"
  }
}

function Emit-JsNamedArray {
  # Returns the lines for:  var <varName> = [<entries...>];
  param([string]$varName, [string[]]$entries)
  $result = @("var $varName = [")
  for ($i = 0; $i -lt $entries.Count; $i++) {
    if ($i -lt $entries.Count - 1) {
      $result += $entries[$i] + ","
    } else {
      $result += $entries[$i]
    }
  }
  $result += "];"
  return $result
}

function Normalize-JsonText {
  param([string]$text)

  if ($text.Length -gt 0 -and $text[0] -eq [char]0xFEFF) {
    $text = $text.Substring(1)
  }

  $normalized = $text -replace "`r`n", "`n"
  $normalized = $normalized -replace "`r", "`n"
  $normalized = $normalized.TrimEnd("`r", "`n")
  return $normalized -replace "`n", "`r`n"
}

$lines = @()
$lines += "// FERROS Harness Constants"
$lines += "// AUTO-GENERATED by tools/generate-harness-constants.ps1"
$lines += "// DO NOT EDIT MANUALLY -- run the generator to regenerate."
$lines += "// Deterministic output -- regenerate and diff to verify freshness."
$lines += "//"
$lines += "// Source:"
$lines += "//   Schemas:  schemas/*.schema.json"
$lines += "//   Fixtures: schemas/fixtures/*.json"
$lines += ""

$fileCount = 0

# --- Schemas ---
$schemaFiles = Get-ChildItem -Path $schemasDir -Filter "*.schema.json" | Sort-Object Name
if ($schemaFiles.Count -eq 0) {
  Write-Warning "No *.schema.json files found in $schemasDir"
}

$lines += "// =================================================="
$lines += "// SCHEMAS"
$lines += "// =================================================="
$lines += ""

foreach ($file in $schemaFiles) {
  $constName = ConvertTo-JsConstName $file.Name
  $raw = Get-Content -Path $file.FullName -Raw -Encoding UTF8

  # Validate JSON
  try {
    $null = $raw | ConvertFrom-Json
  } catch {
    Write-Error "Invalid JSON in schema file: $($file.Name) -- $_"
    exit 1
  }

  $jsonText = Normalize-JsonText $raw

  $lines += "// Source: schemas/$($file.Name)"
  $lines += "var $constName = $jsonText;"
  $lines += ""
  $fileCount++
}

# --- Fixtures ---
$fixtureFiles = Get-ChildItem -Path $fixturesDir -Filter "*.json" | Sort-Object Name
if ($fixtureFiles.Count -eq 0) {
  Write-Warning "No *.json files found in $fixturesDir"
}

$lines += "// =================================================="
$lines += "// FIXTURES"
$lines += "// =================================================="
$lines += ""

$goldenFixtures  = @()
$negativeFixtures = @()

foreach ($file in $fixtureFiles) {
  $constName = ConvertTo-JsConstName $file.Name
  $raw = Get-Content -Path $file.FullName -Raw -Encoding UTF8

  # Validate JSON
  try {
    $null = $raw | ConvertFrom-Json
  } catch {
    Write-Error "Invalid JSON in fixture file: $($file.Name) -- $_"
    exit 1
  }

  $jsonText = Normalize-JsonText $raw

  $lines += "// Source: schemas/fixtures/$($file.Name)"
  $lines += "var $constName = $jsonText;"
  $lines += ""
  $fileCount++

  $stem = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
  $fixtureEntry = "  {name: `"$stem`", file: `"$($file.Name)`", fixture: $constName}"
  if ($file.Name -like "invalid-*") {
    $negativeFixtures += $fixtureEntry
  } else {
    $goldenFixtures += $fixtureEntry
  }
}

# --- Manifests ---
$lines += "// =================================================="
$lines += "// MANIFESTS -- arrays for harness iteration"
$lines += "// =================================================="
$lines += ""

# FERROS_SCHEMAS — named objects for schema lookup
$schemaEntries = @()
foreach ($file in $schemaFiles) {
  $constName = ConvertTo-JsConstName $file.Name
  $stem = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
  $stem = $stem -replace '\.schema$', ''
  $schemaEntries += "  {name: `"$stem`", file: `"$($file.Name)`", schema: $constName}"
}
$lines += Emit-JsNamedArray "FERROS_SCHEMAS" $schemaEntries

# FERROS_GOLDEN_FIXTURES — named objects for fixture lookup
$lines += Emit-JsNamedArray "FERROS_GOLDEN_FIXTURES" $goldenFixtures

# FERROS_NEGATIVE_FIXTURES — named objects for fixture lookup
$lines += Emit-JsNamedArray "FERROS_NEGATIVE_FIXTURES" $negativeFixtures
$lines += ""
$lines += "// Total files embedded: $fileCount"
$lines += "// Schemas: $($schemaFiles.Count) | Golden fixtures: $($goldenFixtures.Count) | Negative fixtures: $($negativeFixtures.Count)"

# --- Write output ---
$outPath = Join-Path $RepoRoot $OutFile
$outDir = [System.IO.Path]::GetDirectoryName($outPath)
if (-not (Test-Path $outDir)) {
  New-Item -ItemType Directory -Path $outDir | Out-Null
}

[System.IO.File]::WriteAllLines($outPath, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Host ""
Write-Host "FERROS Harness Constants generated successfully." -ForegroundColor Green
Write-Host "  Output:   $outPath"
Write-Host "  Schemas:  $($schemaFiles.Count)"
Write-Host "  Fixtures: $($fixtureFiles.Count) ($($goldenFixtures.Count) golden, $($negativeFixtures.Count) negative)"
Write-Host ""
Write-Host "To verify freshness: regenerate and diff against committed output."
Write-Host "  git diff harnesses\_constants.js"
Write-Host ""
